### ISSUE TITLE
Team anmelden

### ISSUE THREAD

**Issue by sepr88** [sepr88/CarND-Capstone#10]
Team Name: ???
Udacity kontaktieren -> Welche Tabelle?

**Comment by mt0726haw** [comment]
Teamnamenvorschläge:
A-Team
smart driving

**Comment by mt0726haw** [comment]
Teamnamenvorschläge:
A-Team
smart driving

**Comment by LucasPucher** [comment]
I like the name!

**Comment by sepr88** [comment]
@LucasPucher @mt0726haw 
Hab uns als A-Team angemeldet. Christoph fehlt noch.

**Comment by sepr88** [comment]
Christoph hinzugefügt
