### ISSUE TITLE
Problems running simulation

### ISSUE THREAD

**Issue by LucasPucher** [sepr88/CarND-Capstone#16]
from utils import tl_utils -> Returns "ImportError: cannot import name tl_utils"

TD_PATH = '/home/basti/Udacity/CarND-Capstone/sim_datasets/raw/tl-set-3'
Dataset not found.

Any ideas?

**Comment by sepr88** [comment]
> from utils import tl_utils -> Returns "ImportError: cannot import name tl_utils"
`cd CarND-Capstone/ros`
`catkin_make && source devel/setup.sh`

> TD_PATH = '/home/basti/Udacity/CarND-Capstone/sim_datasets/raw/tl-set-3
TD_PATH is used as output path if training data collection is active (COLLECT_TD = True). Specify a local path on your machine

**Comment by sepr88** [comment]
@LucasPucher I'll send you a link where you can download the dataset and frozen_inference_graph.pb file. File size was too large for github.

**Comment by LucasPucher** [comment]
For me the problem with utils was solved by modifying "from utils import" to "from src.utils import". Can you check if this change in my branch can be accepted?

**Comment by sepr88** [comment]
@LucasPucher It seems like the packages are not setup correctly. I was able to reproduce your issue and fixed the python setup file. I will push my changes tonight, can you please check if that solves your problem.

Changing the import to src.utils only works within tl_detector

**Comment by sepr88** [comment]
@LucasPucher changes pushed to branch #16-problems-running-simulation. please let me know if that fix works for you

**Comment by LucasPucher** [comment]
Hello Sebastian,

unfortunately the branch you named is identical with my LucasPucher branch. I discovered this when attempting to merge it with my LucasPucher branch.

1. Can you please check if the import in the file tl_detector is:
from src.utils import tl_utils
or
from utils import tl_utils?

2. Whcih setup.py did you change?

**Comment by LucasPucher** [comment]
Ignore my last comment. I found the error, I was messing up with git. Now I was able to run your file and it works.

**Comment by sepr88** [comment]
Changes successfully merged into master. Issue can be closed.
