### ISSUE TITLE
Relative Pfade anstatt absolute Pfadangaben

### ISSUE THREAD

**Issue by sepr88** [sepr88/CarND-Capstone#18]
- [x] Create new folder `ros/src/tl_detector/models`

- [x] Manually add frozen inference graphs from Google Drive to the new folder

- [x] Update path references in `tl_detector.py` @sepr88

**Comment by LucasPucher** [comment]
Can you please include the file tl_label_map.pbtxt for simulation and real scene?

**Comment by LucasPucher** [comment]
I mean upload label file in google drive

**Comment by LucasPucher** [comment]
The changes were written in my LucasPucher branch.
The models should be added in the "data" folder of the directory.
Following names should be used:
sim_frozen_inference_graph.pb
site_frozen_inference_graph.pb
tl_label_map.pbtx

*.pb files are alredy ignored in .gitignore file.

**Comment by sepr88** [comment]
@LucasPucher cherry picked your changes made to `tl_detector.py` #21 

Reopened until tl_label_map.pbtx is added to Google Drive

**Comment by sepr88** [comment]
Added `tl_label_map.pbtxt` and `mscoco_label_map.pbtxt` to Google Drive.
Issue can be closed.
