### ISSUE TITLE
Verify Traffic Light Detection

### ISSUE THREAD

**Issue by sepr88** [sepr88/CarND-Capstone#25]
> After your team has confirmed that traffic light detection is working in the simulator, you should test it out using ROS bags that were recorded at the test site: Traffic Light Detection Test Video.

**Comment by sepr88** [comment]
@ei8852 @mt0726haw  Könnt ihr euch das bitte parallel mal im workspace anschauen. Das sollte unabhängig vom Simulator laufen.

**Comment by sepr88** [comment]
Also, scheinbar wurde in der bereitgestellten rosbag der topic `/current_pose` nicht aufgezeichnet, sondern nur die Kamerabilder:

> path:        traffic_light_training.bag
> version:     2.0
> duration:    2:15s (135s)
> start:       Jan 04 2018 20:40:11.87 (1515094811.87)
> end:         Jan 04 2018 20:42:27.14 (1515094947.14)
> size:        3.6 GB
> messages:    4046
> compression: none [2025/2025 chunks]
> types:       sensor_msgs/Image [060021388200f6f0f447d0fcd9c64743]
> topics:      /image_color   2016 msgs    : sensor_msgs/Image
>              /image_raw     2030 msgs    : sensor_msgs/Image

Das heißt die Bilder werden zwar prinzipiell empfangen aber nicht ausgewertet, da die Klassifikation nur gestartet wird, wenn auch eine Ampel in der Nähe ist. Und ohne `/current_pose` ist keine Distanzberechnung möglich.

Ich habe ja bereits die Bilder aus der rosbag verwendet, um einen zweites Modell zu trainieren (`site_frozen_inference_graph.pb`) und das habe ich auch erfolgreich verifiziert (siehe Google Drive `rosbag_images/classification_test`). 

@mt0726haw @ei8852 @LucasPucher Was meint ihr, sollen wir ungetestet abgeben oder online nach einer anderen rosbag suchen?

**Comment by sepr88** [comment]
Update: Wenn ich die Mindestdistanz zur Ampel ausblende, werden die Bilder korrekt klassifiziert.

**Comment by mt0726haw** [comment]
@sepr88 ich glaub wir versuchens einfach mal
