### ISSUE TITLE
Check Ros Bag

### ISSUE THREAD

**Issue by mt0726haw** [sepr88/CarND-Capstone#28]
https://classroom.udacity.com/nanodegrees/nd013-ent/parts/475eded3-926d-4117-95df-4a2d73df07b6/modules/801fb139-e453-46b0-ae57-36c69edfb717/lessons/8d2ae137-cec6-44c6-9f3c-dacadba2837d/concepts/3251f513-2f82-4d5d-88b6-9d646bbd9101 
Download example and reülay the rosbag

**Comment by sepr88** [comment]
duplicates #25
