### ISSUE TITLE
Submit Project (First Attempt)

### ISSUE THREAD

**Issue by sepr88** [sepr88/CarND-Capstone#29]
@sepr88 @mt0726haw @LucasPucher @ei8852: Bitte alle durchführen
- [ ] Pull branch `origin/#27-relative-paths`:
`git fetch origin`
`git checkout -b origin/#27-relative-paths`
`git pull origin origin/#27-relative-paths`

- [ ] Sicherstellen, dass alle Modelle inkl. Label Maps im Ordner `CarND-Capstone/data` liegen

- [ ] Im Simulator testen

- [ ] Hier im Ticket Rückmeldung geben

**Comment by LucasPucher** [comment]
I did all the steps.
When I created the branch, I got the error "Your local changes to the following files would be overwritten by merge"
I solved by:
git stash save --keep-index
git stash drop

The good news: After ubuntu restart my simulator is working without any timeout! (Black magic)
The simulator is working fine, but when it starts detecting lights, the waypoints are shown behind the car and the controller is not working anymore! I do not think it is the detector but some delay somewhere in the code.
I will try to find the source of the issue and inform you.

**Comment by sepr88** [comment]
@LucasPucher @mt0726haw @ei8852 Bitte **aktuellen** master branch pullen, zippen und hochladen. Vergesst nicht die Modelle im Ordner data abzulegen und build und devel ordner zu löschen.

**Comment by mt0726haw** [comment]
@sepr88 hast du es jetzt bei googleDrive alles hochgeladen? Weil bei mir zeigt es noch nichts an? evtl. dauert es noch.

**Comment by mt0726haw** [comment]
@sepr88 jetzt ist es da passt. super. Die gleiche Idee hatte ich auch das wir alle das gleiche haben.

**Comment by sepr88** [comment]
Ja, ich musste das nochmal hochladen. Datei war größer als 500 MB, da musste ich ein bisschen was rausschmeißen.

**Comment by mt0726haw** [comment]
submitted

**Comment by ei8852** [comment]
submitted

**Comment by LucasPucher** [comment]
submitted
