### ISSUE TITLE
Real world Trainingsdaten in TFRecord 

### ISSUE THREAD

**Issue by sepr88** [sepr88/CarND-Capstone#9]
Umwandeln der Rohdaten in Pascal Voc Format (=jpg + xml) notwendig. Von Voc nach TfRecord bereits vorhanden @sepr88

**Comment by mt0726haw** [comment]
Ich habe den kleinen Datensatz von Bosch verwendet. Es gibt aber auch große mit 1,9GB
Downloadlink:  [https://hci.iwr.uni-heidelberg.de/node/6132](url)

Evtl. nehmen wir noch einen größeren, um mehr Trainingsdaten zu haben. Was meint ihr? 
Hab aber auch gelesen das der kleine Datensatz ausreicht. Das Skript für die Konvertierung lade ich noch hoch. 

Für Interessierte von euch was PascalVoc genau ist folgender Link [http://host.robots.ox.ac.uk/pascal/VOC/pubs/everingham10.pdf](url)

@sepr88  du meintes du hast bereits ein Skript von Pascal_Voc =>TfRecord geschrieben.

**Comment by sepr88** [comment]
@mt0726haw Das Skript findest du hier `<ros/src/tl_detector/light_classification/training/create_pascal_tf_record.py`

**Comment by sepr88** [comment]
@mt0726haw mt0726haw-patch-2 merged with master (#21) .
Issue resolved.
